---
- name: Setup Demo Environment
  hosts: all

  tasks:
    - name: Install AAP and EDA
      ansible.builtin.include_role:
        name: "install_aap_and_eda_on_ocp"

    # Details on how to get a subscription manifest to license AAP can be found here:
    # https://docs.ansible.com/automation-controller/4.4/html/userguide/import_license.html#obtain-sub-manifest
    #
    - name: License AAP
      ansible.controller.license:
        manifest: "{{ aap_manifest_path }}"
        state: present
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
      register: __license_response
      until: __license_response["failed"] == false
      retries: 10
      delay: 30

    - name: Set variables for the infra controller
      ansible.builtin.set_fact:
        controller_hostname: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"

    - name: Load the Kafka demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars/"
        files_matching: "kafka_config.yml"

    - name: Install Kafka if required
      ansible.builtin.include_role:
        name: "install_kafka"
      when: kafka_namespace is defined and kafka_topic_list is defined

    - name: Load the Developer Hub demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars/"
        files_matching: "rhdh_config.yml"

    - name: Install Developer Hub if required
      ansible.builtin.include_role:
        name: "install_rhdh"
      when: rhdh_namespace is defined

    - name: Load the OPA demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars/"
        files_matching: "opa_config.yml"

    - name: Install OPA if required
      ansible.builtin.include_role:
        name: "install_opa"
      when: opa_namespace is defined

    - name: Load the other demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars"
        ignore_files:
          - "kafka_config.yml"
        extensions:
          - "yml"

    - name: Perform the actual demo deployment
      ansible.builtin.include_role:
        name: "deploy_demo"

    - name: Check for post-setup playbook
      ansible.builtin.stat:
        path: "../{{ demo_name | default('demo_devops') }}/playbooks/post_setup.yml"
      register: __post_setup_file

    - name: Run a post-setup playbook if required for further config
      ansible.builtin.include_tasks: "../{{ demo_name | default('demo_devops') }}/playbooks/post_setup.yml"
      when: __post_setup_file.stat.exists

    - name: Display admin password for AAP
      ansible.builtin.debug:
        msg: "AAP Host is: {{ controller_hostname }} and Admin password is: '{{ controller_password }}'"

    - name: Display admin password for EDA
      ansible.builtin.debug:
        msg: "EDA Host is: {{ eda_host }} and EDA Admin password is: '{{ eda_password }}'"

    - name: Display details for Kafka
      ansible.builtin.debug:
        msg: "Kafka Bootstrap Host is: {{ kafkahostname }}:{{ kafkaport | default(9092) }}"
      when: kafkahostname is defined

    - name: Display details for RHDH
      ansible.builtin.debug:
        msg: "Developer Hub Host is: {{ rhdh_hostname }}"
      when: rhdh_hostname is defined
